# Generated by Django 6.1.1 on 2026-09-26 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolclass_is_active_subject_is_active'),
        ('students', '0002_student_contact_name_student_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('ADMISSION', 'Admission'), ('PROMOTION', 'Promotion'), ('REASSIGNMENT', 'Class reassignment'), ('TRANSFER_IN', 'Transfer in'), ('GRADUATION', 'Graduation')], default='ADMISSION', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.classstream')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['student', '-start_date', '-id'],
                'indexes': [models.Index(fields=['student', 'start_date'], name='enrollment_student_start_idx'), models.Index(fields=['class_stream', 'start_date'], name='enrollment_class_start_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='unique_open_enrollment_per_student'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='enrollment_end_after_or_open')],
            },
        ),
    ]
