# Generated by Django 6.1.1 on 2026-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
