# Generated by Django 6.1.1 on 2026-09-23 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='core.term')),
            ],
            options={
                'ordering': ['student', 'term'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10)),
                ('receipt_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.studentfeeaccount')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_charges', to='core.classstream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_charges', to='core.term')),
            ],
            options={
                'ordering': ['class_stream', 'description'],
                'constraints': [models.UniqueConstraint(fields=('class_stream', 'term', 'description'), name='unique_fee_charge')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentfeeaccount',
            constraint=models.UniqueConstraint(fields=('student', 'term'), name='unique_student_term_account'),
        ),
    ]
