# Generated by Django 6.1.1 on 2026-09-24 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolclass_is_active_subject_is_active'),
        ('fees', '0001_initial'),
        ('students', '0002_student_contact_name_student_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feecharge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_charges', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_charges', to='fees.feecharge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_charges', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_charges', to='core.term')),
            ],
            options={
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'term', 'fee_structure'), name='unique_generated_charge'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='charge_amount_positive')],
            },
        ),
    ]
