# Generated by Django 6.1.1 on 2026-09-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2, unique=True)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['min_percent'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weighting_percent', models.PositiveSmallIntegerField(default=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.term')),
            ],
            options={
                'ordering': ['term', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='core.subject')),
            ],
            options={
                'ordering': ['student__admission_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('term', 'name'), name='unique_assessment_per_term'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student', 'assessment', 'subject'), name='unique_mark'),
        ),
    ]
