# Generated by Django 6.1.1 on 2026-09-24 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0003_schoolclass_is_active_subject_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['term', 'class_stream', 'subject', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_assessment_per_term',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('CAT', 'CAT'), ('MID_TERM', 'Mid-Term'), ('END_TERM', 'End-Term'), ('OTHER', 'Other')], default='CAT', max_length=15),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_assessments', to='core.classstream'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_assessments', to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('term', 'class_stream', 'subject', 'name'), name='unique_assessment_per_class_subject'),
        ),
    ]
