# Generated by Django 6.1.1 on 2026-09-24 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_assessment_options_and_more'),
        ('core', '0003_schoolclass_is_active_subject_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='class_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_assessments', to='core.classstream'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_assessments', to='core.subject'),
        ),
    ]
